### PR TITLE
Add syntax highlighting to ruby code on README

### PR DESCRIPTION
**Pull request by edgurgel**
Preview: https://github.com/edgurgel/cactus/blob/patch-1/README.md

### CODE REVIEW

**Comment by sadjow** [comment]
:+1: +1

**Comment by winston** [comment]
Hi! Looks good.. But technically, the `Cactus.expect` lines are not Ruby code. 
Does the highlighting still works if you change it to javascript?

Thanks!

**Comment by edgurgel** [comment]
Fixed!

**Comment by winston** [comment]
Merged. Thanks!

**Pull request merged**
